### ISSUE TITLE
Link in article references another repo

### ISSUE THREAD

**Issue by andersfrank** [CodingAleCR/picker-plus-swift#1]
Hi, 
I read your article at https://blog.logrocket.com/build-swiftui-segmented-customizable-control/. The link to the source code in the article does not lead to this project, but instead to another repo: https://github.com/CodingAleCR/dayswithoutincidents/tree/v3.0.0%2B11.

Cheers

**Comment by CodingAleCR** [comment]
I'll try to get it fixed as soon as possible.

Thank you for pointing that out @andersfrank and for reading the article, it means a lot to me.
